name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate github-contribution-grid-snake.svg
        uses: avelino/github-contribution-grid-snake-action@v0.5.0
        with:
          github_user_name: hariskokane
          outputs: |
            output/github-contribution-grid-snake-dark.svg?palette=github-dark
            output/github-contribution-grid-snake.gif?color_snake=4ECDC4&color_dots=#0D1117,#0e4429,#006d32,#26a641,#39d353

      - name: Push github-contribution-grid-snake.svg to 'output' branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
